source 'https://github.com/CocoaPods/Specs.git'

target 'NGORoundedButton', :exclusive => true do
  pod "NGORoundedButton", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "NGORoundedButton", :path => "../"

  
end
